export const eletropostos = [
  {
    id: 1,
    nome: "Shopping Iguatemi",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Av. Brigadeiro Faria Lima, 2232",
    score: 9.4,
    carregadores: 4,
    disponiveis: 3,
    conectores: ["CCS2", "CHAdeMO", "Tipo 2"],
    potencia: "150 kW",
    horario: "08:00 - 22:00",
    comodidades: ["Estacionamento", "Shopping", "Alimentação"],
    lat: -23.5752,
    lng: -46.6890,
  },
  {
    id: 2,
    nome: "Hotel Fasano",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Rua Vittorio Fasano, 88",
    score: 9.1,
    carregadores: 3,
    disponiveis: 2,
    conectores: ["CCS2", "Tipo 2"],
    potencia: "100 kW",
    horario: "24 horas",
    comodidades: ["Manobrista", "Hotel", "Restaurante"],
    lat: -23.5614,
    lng: -46.6597,
  },
  {
    id: 3,
    nome: "Posto Shell Paulista",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Av. Paulista, 1000",
    score: 8.8,
    carregadores: 2,
    disponiveis: 1,
    conectores: ["CCS2", "CHAdeMO"],
    potencia: "50 kW",
    horario: "24 horas",
    comodidades: ["Posto de Combustível", "Conveniência"],
    lat: -23.5630,
    lng: -46.6543,
  },
  {
    id: 4,
    nome: "Parque Villa-Lobos",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Av. Professor Fonseca Rodrigues, 2001",
    score: 8.5,
    carregadores: 6,
    disponiveis: 4,
    conectores: ["Tipo 2", "CCS2"],
    potencia: "22 kW",
    horario: "06:00 - 20:00",
    comodidades: ["Estacionamento", "Parque", "Ciclovia"],
    lat: -23.5407,
    lng: -46.7172,
  },
  {
    id: 5,
    nome: "Shopping JK Iguatemi",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Av. Presidente Juscelino Kubitschek, 2041",
    score: 9.2,
    carregadores: 8,
    disponiveis: 5,
    conectores: ["CCS2", "CHAdeMO", "Tipo 2", "Tesla"],
    potencia: "250 kW",
    horario: "10:00 - 22:00",
    comodidades: ["Estacionamento", "Shopping", "Alimentação", "Wi-Fi"],
    lat: -23.5965,
    lng: -46.6857,
  },
];

export const avaliacoes = [
  {
    id: 1,
    eletroposto: "Shopping Iguatemi",
    eletroposto_id: 1,
    autor: "Carlos M.",
    tempo: "Há 2 horas",
    estrelas: 5,
    comentario: "Perfeito! Sempre funcionando.",
    aprovado: false,
  },
  {
    id: 2,
    eletroposto: "Hotel Fasano",
    eletroposto_id: 2,
    autor: "Ana P.",
    tempo: "Há 4 horas",
    estrelas: 4,
    comentario: "Bom, mas às vezes tem fila.",
    aprovado: false,
  },
  {
    id: 3,
    eletroposto: "Posto Shell Paulista",
    eletroposto_id: 3,
    autor: "Roberto S.",
    tempo: "Há 1 dia",
    estrelas: 4,
    comentario: "Rápido e prático, ótima localização.",
    aprovado: true,
  },
  {
    id: 4,
    eletroposto: "Shopping JK Iguatemi",
    eletroposto_id: 5,
    autor: "Fernanda L.",
    tempo: "Há 2 dias",
    estrelas: 5,
    comentario: "Melhor eletroposto de SP! Ultra-rápido.",
    aprovado: true,
  },
];

export const evs = [
  {
    id: 1,
    modelo: "Tesla Model 3 Long Range",
    ano: 2024,
    preco: 349990,
    bateria: 82,
    autonomia: 614,
    score: 9.4,
  },
  {
    id: 2,
    modelo: "VW ID.4 Pro",
    ano: 2024,
    preco: 289990,
    bateria: 77,
    autonomia: 520,
    score: 8.9,
  },
  {
    id: 3,
    modelo: "BYD Han",
    ano: 2024,
    preco: 319990,
    bateria: 85,
    autonomia: 550,
    score: 9.1,
  },
  {
    id: 4,
    modelo: "Volvo EX40",
    ano: 2024,
    preco: 279990,
    bateria: 69,
    autonomia: 480,
    score: 8.7,
  },
];

export const relatorios = {
  recargasNoMes: 28547,
  regioes: [
    { nome: "São Paulo - SP", eletropostos: 342, recargas: 8547 },
    { nome: "Rio de Janeiro - RJ", eletropostos: 187, recargas: 4231 },
    { nome: "Belo Horizonte - MG", eletropostos: 98, recargas: 2100 },
  ],
  oportunidades: [
    {
      regiao: "Região Sul - PR",
      descricao: "Alta demanda com baixa cobertura. Oportunidade para 45+ novos pontos.",
    },
    {
      regiao: "Nordeste - CE",
      descricao: "Crescimento de 32% na frota EV sem infraestrutura adequada.",
    },
  ],
};